<div class="loadingio-spinner-rolling-aq47spj5sc7">
  <div class="ldio-li3z4kvcp2">
    <div></div>
  </div>
</div>;
const style = `
@keyframes ldio-li3z4kvcp2 {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-li3z4kvcp2 div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #2a4365;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-li3z4kvcp2 div {
  animation: ldio-li3z4kvcp2 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-aq47spj5sc7 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-li3z4kvcp2 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-li3z4kvcp2 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
`;
